name: LastFM Monthly Run

on:
  schedule:
    # Runs At 14:30UTC (08:00PM IST) on every 1st day of the month.
    - cron: '30 14 1 * *'
  workflow_dispatch:  # Allows manual triggering
    
jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
      LASTFM_USERNAME: ${{ secrets.LASTFM_USERNAME }}
      TELE_BOT_TOKEN: ${{ secrets.TELE_BOT_TOKEN }}
      TELE_CHNANNEL_ID: ${{ secrets.TELE_CHNANNEL_ID }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set timezone
      uses: szenius/set-timezone@v2.0
      with:
        timezoneLinux: "Asia/Kolkata"
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run script
      env:
        LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
        LASTFM_USERNAME: ${{ secrets.LASTFM_USERNAME }}
        TELE_BOT_TOKEN: ${{ secrets.TELE_BOT_TOKEN }}
        TELE_CHNANNEL_ID: ${{ secrets.TELE_CHNANNEL_ID }}    
      run: python main.py 2
